---
name: {{ name }} Security Scan

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *"

permissions:
  contents: read
  id-token: write

jobs:
  scheduled-security-scan:
    uses: coreeng/p2p/.github/workflows/p2p-workflow-security-scan.yaml@v1
    secrets:
      env_vars: {% raw %}${{ secrets.env_vars }}{% endraw %}
    with:
      app-name: {{ name }}
      tenant-name: {{ tenant }}
      security-scan-blocking-severity: "off"
{%- if working_directory is defined and working_directory %}
      working-directory: {{ working_directory }}
{%- endif %}
