{{- $registry := .Values.registry | required ".Values.registry is required." -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reference-service
  labels:
    app.kubernetes.io/name: reference-service
spec:
  replicas: {{ .Values.service.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: reference-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: reference-service
    spec:
      containers:
        - name: reference-service
          image: {{ $registry }}/{{ .Values.service.image }}:{{ .Values.tag }}
          resources:
            requests:
              cpu: "700m"
              memory: "64Mi"
            limits:
              memory: "128Mi"
          livenessProbe:
            httpGet:
              port: 8081
              path: /internal/status
          readinessProbe:
            httpGet:
              port: 8080
              path: /hello
          {{- if .Values.service.environmentVariables }}
          env:
            {{- range $key, $value := .Values.service.environmentVariables }}
            - name: {{ $key }}
              value: {{ $value }}
          {{- end }}
          {{- end }}
          ports:
            - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiremock
  labels:
    app.kubernetes.io/name: wiremock
spec:
  replicas: {{ .Values.wiremock.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: wiremock
  template:
    metadata:
      annotations:
        timestamp: {{ now | quote }}
      labels:
        app.kubernetes.io/name: wiremock
    spec:
      containers:
        - name: wiremock
          image: {{ .Values.wiremock.image }}
          args: [ "--no-request-journal", "--disable-request-logging", "--async-response-enabled", "true" ]
          volumeMounts:
            - name: wiremock-mappings
              mountPath: /home/wiremock/mappings
          resources:
            requests:
              cpu: "700m"
              memory: "256Mi"
            limits:
              memory: "512Mi"
          livenessProbe:
            httpGet:
              port: 8080
              path: /static
          readinessProbe:
            httpGet:
              port: 8080
              path: /static
          ports:
            - containerPort: 8080
      volumes:
        - name: wiremock-mappings
          configMap:
            name: wiremock-mappings