---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: reference-service
  name: reference-service
spec:
  selector:
    app.kubernetes.io/name: reference-service
  ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: metrics
      protocol: TCP
      port: 8081
      targetPort: 8081
{{- if .Values.wiremock.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: wiremock
spec:
  selector:
    app.kubernetes.io/name: wiremock
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.wiremock.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: wiremocks
spec:
  clusterIP: None # headless
  selector:
    app.kubernetes.io/name: wiremock
  ports:
    - protocol: TCP
      port: {{ .Values.wiremock.port }}
      targetPort: {{ .Values.wiremock.port }}
{{- end }}
