version: 1

source:
  secrets:
    - id: 7bb0f54e02ff3c42d654a0d6f2c91c2176058ba268cf02b02f1dd0d3941a5695
      path: yarn.lock
      reason: False positive in Yarn lockfile checksum; no credential material.
    - id: 4904adc4778dc1f1415726bdef669c0e4896208765c723485be778b3f75665ee
      path: yarn.lock
      reason: False positive in Yarn lockfile checksum; no credential material.
