---
# Template YAML Schema

name: str()
description: str()
kind: subset(enum('app', 'infra'))
skeletonPath: str()
config: include('config', required=False)

---
# Config schema
config:
  replicas: int(min=0)
  autoscaling:
    enabled: bool()
    minReplicas: int(min=1)
    maxReplicas: int(min=1)
    targetCPUUtilizationPercentage: int(min=1, max=100)
  resources:
    limits:
      cpu: str()
      memory: str()
