registry:
domain:
appUrlSuffix:
tenantName:
tag: latest
monitoring: false
dashboarding: false
prometheusEndpoint: http://frontend.platform-monitoring.svc:9090

functional:
  image: go-reference-app-functional
nft:
  image: go-reference-app-nft
  endpoint: ingress
  resources:
    requests:
      cpu: 1000m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 512Mi
extended:
  image: go-reference-app-extended
  endpoint: service
  parallelism: 10
  resources:
    requests:
      cpu: 1000m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 512Mi
service:
  image: go-reference-app
  replicas: 2
  resources:
    requests:
      cpu: 700m
      memory: 50Mi
    limits:
      cpu: 700m
      memory: 100Mi
  environmentVariables:
    DOWNSTREAM_ENDPOINT: "http://wiremock"
wiremock:
  enabled: false
  image: wiremock/wiremock:3.4.2
  replicas: 2
  port: 8080
  resources:
    requests:
      cpu: 700m
      memory: 256Mi
    limits:
      cpu: 700m
      memory: 512Mi
