management:
  server:
    port: 8081
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, prometheus
  endpoint:
    status.enabled: true
    shutdown.enabled: false
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  graphite:
    metrics:
      export:
        enabled: false

server:
  shutdown: GRACEFUL
  grace-period: 30s
  drainingMs: 0

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  lifecycle:
    timeout-per-shutdown-phase: 30s