server:
  port: 8080
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
management:
  server:
    port: 8081
  endpoints:
    web:
      base-path: /
      exposure:
        include: health,prometheus
