appName: {{ name }}
registry:
domain:
appUrlSuffix:
tenantName:
tag: latest
monitoring: false
dashboarding: false
prometheusEndpoint:

functional:
  image:
  resources:
    requests:
      cpu: 0m
      memory: 1024Mi
    limits:
      memory: 1024Mi
nft:
  image:
  endpoint: ingress
  resources:
    requests:
      cpu: 1000m
      memory: 1024Mi
    limits:
      memory: 1024Mi
integration:
  image:
  resources:
    requests:
      cpu: 0m
      memory: 1024Mi
    limits:
      memory: 1024Mi
extended:
  image:
  endpoint: service
  parallelism: 10
  resources:
    requests:
      cpu: 1000m
      memory: 1024Mi
    limits:
      cpu: 1000m
      memory: 1024Mi
service:
  image:
  replicas: 2
  resources:
    requests:
      cpu: 700m
      memory: 1024Mi
    limits:
      memory: 1024Mi
