appName:
registry:
domain:
appUrlSuffix:
tenantName:
tag: latest
monitoring: false
dashboarding: false
prometheusEndpoint:

functional:
  image:
nft:
  image:
  endpoint: ingress
  resources:
    requests:
      cpu: 1000m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 512Mi
extended:
  image:
  endpoint: service
  parallelism: 10
  resources:
    requests:
      cpu: 1000m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 512Mi
service:
  image:
  replicas: 1
  environmentVariables:
    JVM_OPTS: "-Xmx100m -Xms100m"
  resources:
    requests:
      cpu: 700m
      memory: 300Mi
    limits:
      cpu: 700m
      memory: 300Mi