---
name: Trigger Rendering Workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  trigger-rendering:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/github-script@v8
        with:
          github-token: ${{ secrets.TEMPLATES_RENDER_GH_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'coreeng',
              repo: 'core-platform-reference-applications',
              workflow_id: 'render-templates.yaml',
              ref: 'main'
            })
